import { Course } from './types.ts';

// A curated list of high-impact IT courses to be generated by AI
export const COURSE_CATALOG: Course[] = [
  {
    id: 'full-stack-web-development',
    title: 'Full-Stack Web Development',
    description: 'Master front-end and back-end technologies to build complete web applications.',
    longDescription: 'Embark on a comprehensive journey to become a full-stack developer. This course covers everything from crafting beautiful user interfaces with React and TypeScript to building robust server-side applications with Node.js, Express, and databases. You will learn to architect, build, and deploy real-world projects from scratch.',
    imageUrl: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    moduleImagePool: [
        'https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', // React
        'https://images.unsplash.com/photo-1599507593499-a3f7d7d97667?q=80&w=1974&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', // Node.js
        'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=2070&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', // Code
        'https://images.unsplash.com/photo-1516116216624-53e697309957?q=80&w=2070&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', // Database
        'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=2070&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', // Laptop with code
    ]
  },
  {
    id: 'machine-learning-engineering',
    title: 'Machine Learning Engineering',
    description: 'From data processing to model deployment, become a proficient ML Engineer.',
    longDescription: 'Dive into the world of Machine Learning. This course takes you from the fundamentals of data science with Python (Pandas, NumPy) to building and evaluating complex models with Scikit-learn and TensorFlow. You will learn the complete lifecycle of an ML project, including deployment and MLOps principles.',
    imageUrl: 'https://images.unsplash.com/photo-1555255707-c07966088b7b?q=80&w=1974&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
     moduleImagePool: [
        'https://images.unsplash.com/photo-1507146426996-321341aa1ac5?q=80&w=2070&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', // Data Science
        'https://images.unsplash.com/photo-1678483749033-6a892a1a7801?q=80&w=2070&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', // Neural Network
        'https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?q=80&w=1974&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', // Data analysis
        'https://images.unsplash.com/photo-1614064548237-02f0d1a24b3d?q=80&w=2070&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', // Python code
    ]
  },
   {
    id: 'aws-cloud-architecture',
    title: 'AWS Cloud Architecture',
    description: 'Design and deploy scalable, highly available, and fault-tolerant systems on AWS.',
    longDescription: 'Become an AWS expert. This course is designed to prepare you for the AWS Certified Solutions Architect exam. You will gain deep knowledge of core AWS services like EC2, S3, VPC, RDS, and Lambda. Learn to architect secure, cost-effective solutions for a variety of use cases.',
    imageUrl: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?q=80&w=2831&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
     moduleImagePool: [
        'https://images.unsplash.com/photo-1605379399642-870262d3d051?q=80&w=2706&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        'https://images.unsplash.com/photo-1593720213428-28a5b9e94613?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        'https://images.unsplash.com/photo-1550439062-609e1531270e?q=80&w=2820&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        'https://images.unsplash.com/photo-1556075798-4825dfaaf498?q=80&w=2940&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    ]
  },
   {
    id: 'advanced-cybersecurity',
    title: 'Advanced Cybersecurity',
    description: 'Protect systems and networks from digital attacks with advanced security techniques.',
    longDescription: "Go beyond the basics and delve into the world of offensive and defensive security. This course covers network security, ethical hacking, cryptography, and incident response. You'll learn to think like an attacker to build more secure systems and gain hands-on experience with modern security tools.",
    imageUrl: 'https://images.unsplash.com/photo-1510915228340-29c85a43dcfe?q=80&w=2070&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
     moduleImagePool: [
        'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=2070&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', // Matrix code
        'https://images.unsplash.com/photo-1614064548237-02f0d1a24b3d?q=80&w=2070&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', // Padlock on code
        'https://images.unsplash.com/photo-1593168132939-e6793f02541a?q=80&w=2070&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', // Hacker
        'https://images.unsplash.com/photo-1543286386-713bdd548da4?q=80&w=2070&auto=format&fit=crop&ixlib-rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', // Security analytics
    ]
  },
];


export const MOCK_PROGRESS_DATA = [
  { week: 'Week 1', xp: 400 },
  { week: 'Week 2', xp: 300 },
  { week: 'Week 3', xp: 500 },
  { week: 'Week 4', xp: 280 },
  { week: 'Week 5', xp: 450 },
  { week: 'Week 6', xp: 320 },
  { week: 'Week 7', xp: 600 },
];